### ISSUE TITLE
CreateRequestContainer doesn't tag the new LifeTimeScope

### ISSUE THREAD

**Issue by HughLacey** [NancyFx/Nancy.Bootstrappers.Autofac#23]
We have had a problem with a windows service that was self hosting Nancy - the working memory set was increasing on every request to Nancy.

Our first thought was to move registration of nancy types into the ConfigureRequestContainer override but in order to register types using the InstancePerRequest() extension method the lifetimescope must be tagged with the appropriate tag, we worked round this with:

protected override ILifetimeScope CreateRequestContainer(NancyContext context)
        {
            return ApplicationContainer.BeginLifetimeScope(MatchingScopeLifetimeTags.RequestLifetimeScopeTag);
        }

Shouldn't this be the default behaviour?

**Comment by khellang** [comment]
@HughLacey Yeah. Nancy doesn't support using the `InstancePerRequest` method today, so all your request-scoped instances wouldn't be disposed. This method hasn't traditionally been a part of Autofac core, but has been [added (relatively) recently](https://github.com/autofac/Autofac/commit/78e3ff71286fab6185ea8a89ae622825afa741a5). I've sent a PR, #24, to add support for this scenario :smile:
