### ISSUE TITLE
Consider separating registration semantics from resolution

### ISSUE THREAD

**Issue by tillig** [NancyFx/Nancy.Bootstrappers.Autofac#60]
I'm working through some issues [like this one](https://github.com/autofac/Autofac/issues/780) and [this one](https://github.com/autofac/Autofac/issues/608) in Autofac trying to figure out where `container.Update` gets used and why.

Something I noticed is that in [`NancyBootstrapperWithRequestContainerBase`](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyBootstrapperWithRequestContainerBase.cs) and, subsequently, [the Autofac implementation of it](https://github.com/NancyFx/Nancy.Bootstrappers.Autofac/blob/master/src/Nancy.Bootstrappers.Autofac/AutofacNancyBootstrapper.cs) that the application container (an `ILifetimeScope` in this case) gets updated with registrations rather than having them present during initial container build in the first place. This can cause challenges with some things like `AutoActivate` and `IStartable` components. Using `Update` is generally also a red flag to me because it means if something has already been resolved out of the container (unlikely, but possible) then it could be inconsistent with the same service type that gets resolved _post Update_.

Have you considered separating _resolution_ of bootstrapper components (the `Get` methods on the bootstrapper class) from the _registration_ of components (the `Register` tasks)?

I do recognize you may be pretty far down the path to make such a change, but I figured I'd ask.

**Comment by khellang** [comment]
The short answer is; yes :wink:

We realize that this is suboptimal, but there's not much we can do about it using the existing design. We've prototyped a new version of the Nancy bootstrapper that allows this. You can check it out [here](https://github.com/khellang/nancy-bootstrapper-prototype/blob/master/src/Nancy.Bootstrappers.Autofac/AutofacBootstrapper.cs)

**Comment by tillig** [comment]
Oh, yup, that looks way better. Cool beans, that prototype looks nice. Thanks for the pointer!
